### ISSUE TITLE
About EOFError

### ISSUE THREAD

**Issue by sibaek-lee** [eriksandstroem/Loopy-SLAM#5]
/home/localization/.local/lib/python3.10/site-packages/joblib/externals/loky/backend/resource_tracker.py:330: UserWarning: resource_tracker: /tmp/joblib_memmapping_folder_2137_1329420a098843ed94921c9aa0c3d379_fca000de14434f40abfc654bdcccecb6: FileNotFoundError(2, 'No such file or directory')
  warnings.warn(f"resource_tracker: {name}: {e!r}")
Process mapper:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home0/localization/workspace/sibaek/Loopy-SLAM/src/Point_SLAM.py", line 232, in mapping
    self.mapper.run(time_string)
  File "/home0/localization/workspace/sibaek/Loopy-SLAM/src/Mapper.py", line 1028, in run
    self.logger.log(idx, self.keyframe_dict_global, self.keyframe_list_global,
  File "/home0/localization/workspace/sibaek/Loopy-SLAM/src/utils/Logger.py", line 61, in log
    'fragments' : npc.get_fragments(),
  File "<string>", line 2, in get_fragments
  File "/opt/conda/lib/python3.10/multiprocessing/managers.py", line 818, in _callmethod
    kind, result = conn.recv()
  File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

Hello, I encountered the following error. This error seems to occur either when saving the checkpoint or at the very last frame of the process. I was wondering if it would be possible for you to check whether the code is running properly.

**Comment by sibaek-lee** [comment]
I solved the issue. It was related to the shared memory of the Docker container, and expanding the container's shared memory size resolved it.

**Comment by Jfsslemos** [comment]
I am facing the same issue but without docker. Following is the traceback 

Traceback (most recent call last):
  File "/home/jota/anaconda3/envs/loopy-slam/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/jota/anaconda3/envs/loopy-slam/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jota/mestrado/Loopy-SLAM/src/Point_SLAM.py", line 232, in mapping
    self.mapper.run(time_string)
  File "/home/jota/mestrado/Loopy-SLAM/src/Mapper.py", line 960, in run
    _ = self.optimize_map(num_joint_iters, idx, gt_color, gt_depth, gt_c2w,
  File "/home/jota/mestrado/Loopy-SLAM/src/Mapper.py", line 485, in optimize_map
    transformed_camera = self.npc.apply_transformation()
  File "<string>", line 2, in apply_transformation
  File "/home/jota/anaconda3/envs/loopy-slam/lib/python3.10/multiprocessing/managers.py", line 818, in _callmethod
    kind, result = conn.recv()
  File "/home/jota/anaconda3/envs/loopy-slam/lib/python3.10/multiprocessing/connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "/home/jota/anaconda3/envs/loopy-slam/lib/python3.10/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/home/jota/anaconda3/envs/loopy-slam/lib/python3.10/multiprocessing/connection.py", line 388, in _recv
    raise EOFError
EOFError
